# Generated by Django 4.2.5 on 2023-11-16 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_name_room_location_room_host_room_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='contact',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
