# Generated by Django 4.2.5 on 2023-12-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_room_city_alter_room_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.TextField(default='event', null=True),
        ),
    ]
