# Generated by Django 4.2.5 on 2023-12-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
