# Generated by Django 4.2.5 on 2024-01-26 14:40

from django.db import migrations
import django.db.models.functions.math


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_district_room_state_alter_room_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': [django.db.models.functions.math.Random()]},
        ),
        migrations.RemoveField(
            model_name='room',
            name='district',
        ),
    ]
