# Generated by Django 4.2.5 on 2024-01-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_room_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='district',
        ),
    ]
