# Generated by Django 4.2.5 on 2024-01-26 16:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_remove_room_district'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Post',
        ),
    ]
