# Generated by Django 4.2.5 on 2024-01-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
